[package]
name = "login_app"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "^0.19"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Window", "Document"] }
wasm-logger = "0.2"
log = "0.4"